FUZZ_OBJS   = fuzz/address.o

CFLAGS	+= -I$(SRCDIR)/fuzz

FUZZ_ADDRESS = fuzz/address-fuzz$(EXEEXT)

.PHONY: fuzz
fuzz: $(FUZZ_ADDRESS)

$(FUZZ_ADDRESS): $(FUZZ_OBJS) $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS)
	$(CXX) -o $@ $(FUZZ_OBJS) $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS) $(LDFLAGS) $(LIBS)

all-fuzz: $(FUZZ_ADDRESS)

clean-fuzz:
	$(RM) $(FUZZ_ADDRESS) $(FUZZ_OBJS) $(FUZZ_OBJS:.o=.Po)

install-fuzz:
uninstall-fuzz:

FUZZ_DEPFILES = $(FUZZ_OBJS:.o=.Po)
-include $(FUZZ_DEPFILES)

# vim: set ts=8 noexpandtab:
